### ISSUE TITLE
`vim --version` hangs on GitHub Actions Windows runner

### ISSUE THREAD

**Issue by rhysd** [vim/vim#15372]
### Steps to reproduce

First, prepare the following GitHub Actions workflow for reproducing this issue.

```yaml
name: Bug
on: push

jobs:
  bug:
    runs-on: windows-latest
    steps:
      - run: Invoke-WebRequest https://github.com/vim/vim-win32-installer/releases/download/v9.1.0631/gvim_9.1.0631_x64.zip -OutFile gvim_9.1.0631_x64.zip
      - run: Expand-Archive gvim_9.1.0631_x64.zip unzipped
      - run: unzipped/vim/vim91/vim.exe --version
```

Then push the workflow to your remote repository on GitHub.

The workflow hangs at the following step without any output to stdout and stderr:

```yaml
- run: unzipped/vim/vim91/vim.exe --version
```

This is my reproduction: https://github.com/rhysd/misc/actions/runs/10131456929/job/28014171927

I'm maintaining [the action to setup Vim](https://github.com/rhysd/action-setup-vim) for testing plugins on CI. The repository has a CI workflow for weekly check. On the last week it ran successfully but this week it didn't.

I noticed that `vim.exe --version` hung. I manually bisected this issue with versions of Vim released on vim-win32-installer.

- 9.1.0631 hangs
- 9.1.0626 doesn't hang
- 9.1.0618 doesn't hang

So I guess there was some regression on Vim after 9.1.0626. This repro uses x64 version of Vim but x86 version also reproduces this issue.

Related to: https://github.com/rhysd/action-setup-vim/issues/37

### Expected behaviour

I expected that the workflow ran successfully with outputting the version information.

### Version of Vim

9.1.0631

### Environment

- Operating system: Windows (`windows-latest` runner on GitHub Actions)
- Shell: Powershell
- `$TERM`: Nothing
