### ISSUE TITLE
vim/runtime/indent/yaml.vim indent breaks visual insert <C-V><S-I>

### ISSUE THREAD

**Issue by dezza** [vim/vim#2324]
I believe 
https://github.com/vim/vim/blob/d07969093a9b3051511c478d71c36de6fc33c0d6/runtime/indent/yaml.vim
has some indent settings that trigger when inserting in visual-selection `<C-V><S-I>`
```yaml
- hosts: ubuntu
  
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- hosts:        all
  gather_facts: true
  remote_user:  root
  pre_tasks:
  - name:       provision ssl dir
    file:
      dest:     /etc/ssl/private
      state:    directory
      owner:    root
      group:    root
      mode:     0700

  - name:       copy ssl certificates
    copy:
      src:      files/ssl/{{ item }}
      dest:     /etc/ssl/private/{{ item }}
      owner:    root
      group:    root
      mode:     0600
    with_items:
    - server.key.pem
    - server.crt.pem


  roles:
    - role:     bennojoy.mysql
    - role:     Ginsys.seafile
    - role:     Ginsys.nginx


  post_tasks:
  - name:       allow web server access to seafile data
    user:
      name:     'www-data'
      groups:   '{{ seafile_user }}'
      append:   yes
```

Trying to do `<C-V>9j<S-I>#<ESC>` to insert a comment over

```yaml
  - name:       copy ssl certificates
    copy:
      src:      files/ssl/{{ item }}
      dest:     /etc/ssl/private/{{ item }}
      owner:    root
      group:    root
      mode:     0600
    with_items:
    - server.key.pem
    - server.crt.pem
```

Results in

```yaml
      #- name:       copy ssl certificates
    co#- napy:
      #- nasrc:      files/ssl/{{ item }}
      #- nadest:     /etc/ssl/private/{{ item }}
      #- naowner:    root
      #- nagroup:    root
      #- namode:     0600
    wi#- nath_items:
    - #- naserver.key.pem
    - #- naserver.crt.pem
```

I believe this only happens when this is nested under a parent-key.

My indent settings:
```vim
set autoindent
```

Turning off indentexpr removes the symptom
```vim
setlocal indentexpr=
```
