### ISSUE TITLE
vim paste with "#"

### ISSUE THREAD

**Issue by weironz** [vim/vim#4366]
The following problems occurred when I opened vim and pasted content with #.
vi command No problem.

vim test.yml
```
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
          #         - name: MYSQL_ROOT_PASSWORD
          #                   value: password
          #                           ports:
          #                                   - containerPort: 3306
          #                                             name: mysql
          #                                                     volumeMounts:
          #                                                             - name: mysql-persistent-storage
          #                                                                       mountPath: /var/lib/mysql
          #                                                                             volumes:
          #                                                                                   - name: mysql-persistent-storage
          #                                                                                           persistentVolumeClaim:
          #                                                                                                     claimName: mysql-pv-claim
```
