### ISSUE TITLE
Syntax coloring for YAML files breaks on some quotes

### ISSUE THREAD

**Issue by UnitedMarsupials** [vim/vim#8234]
**Describe the bug**
The syntax coloring for the YAML files messes up the colors in many situations...

**To Reproduce**
Try this YAML text in gvim:
```yml
 name: Get full list of services for {{ inp | join(', ') }}
  register: newservices
  changed_when: False
  check_mode: ansible_check_mode
  command: |-
    xmllint -format -pretty 1 -xpath /Foo/Bar
```

**Expected behavior**
Something similar to (or better than) how GitHub's syntax-coloring code renders it above.

**Screenshots**
Note, how the "text" begins on the second quote -- and never ends:
![image](https://user-images.githubusercontent.com/64500027/119193867-46a06980-ba50-11eb-8b15-6b07a2951c83.png)

**Environment (please complete the following information):**
 - Vim version 8.2.1110
 - FreeBSD/11
 - GUI
